/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.pipeline.audio;

import dev.syndicate.model.AudioMaterial;

/**
 * The synthesis primitives every sound in the bank is built from
 * (docs/15_vehicle_preparation_pipeline.md#D15-S8, D15-R38).
 *
 * <p><b>Why synthesis rather than samples.</b> D15-R38 ranks sourcing: permissively licensed
 * libraries first, procedural synthesis second, commissioned audio third — and rules generative
 * models out for loops because of the seam. Synthesis is chosen here for the whole bank, and the
 * deciding reason is the one D15-R39 raises: every audio asset has to record a licence, and the two
 * shipped car models are already CC-BY-NC-SA. Sound generated by this file carries the repository's
 * own terms and adds no second, differently-encumbered set nobody is tracking. It is also
 * reproducible — the same code produces the same bytes, so a regenerated bank is a no-op diff — and
 * it is parametric, which is what D15-S8 asks for from the engine and tyre loops anyway.
 *
 * <p><b>Impacts are modal, not noise.</b> What makes a struck object sound like metal rather than
 * like plastic is the set of frequencies it rings at, how inharmonic they are, and how long each
 * takes to decay. That is a handful of exponentially-damped sinusoids — a modal model — and it is
 * both cheaper and more convincing than filtering noise, because the ear identifies material from
 * decay time and partial spacing far more than from spectral tilt.
 *
 * <p>All randomness comes from a caller-supplied seed, so the bank is deterministic (G4's habit,
 * applied to content generation).
 */
public final class SoundSynth {

    private SoundSynth() {
        throw new AssertionError("no instances");
    }

    /**
     * The acoustic character of one material: what it rings at, and for how long.
     *
     * @param partials frequency ratios of the modes above {@link #baseHz}. Inharmonic ratios are
     *     what a struck plate or a bell has; harmonic ones sound like a string and read as musical
     * @param baseHz the lowest mode's frequency for a reference-sized object
     * @param decaySeconds how long the lowest mode takes to fall by 60 dB
     * @param decaySpread how much faster each higher mode decays; high partials always die first,
     *     which is why a struck object gets duller as it rings out
     * @param transientSeconds the length of the broadband click of the strike itself
     * @param transientLevel how loud that click is relative to the modes
     * @param brightnessHz the centre of the transient's band-pass
     */
    public record MaterialVoice(
            double[] partials,
            double baseHz,
            double decaySeconds,
            double decaySpread,
            double transientSeconds,
            double transientLevel,
            double brightnessHz) {}

    /**
     * The measured-by-ear character of each audio material.
     *
     * <p>Metal rings longest and most inharmonically; glass is short, very bright and nearly pure;
     * rubber barely rings at all and is almost entirely transient; plastic is a dull short knock;
     * composite cracks — a short bright transient over a fast-decaying low mode, which is what
     * delamination sounds like rather than the ring of a metal panel.
     */
    public static MaterialVoice voiceOf(AudioMaterial material) {
        return switch (material) {
            case METAL -> new MaterialVoice(
                    new double[] {1.0, 2.76, 5.40, 8.93, 13.34, 18.64}, 210.0, 1.60, 2.2, 0.004, 0.45, 3200.0);
            case GLASS -> new MaterialVoice(
                    new double[] {1.0, 2.32, 4.18, 6.95, 10.4}, 1850.0, 0.42, 2.8, 0.002, 0.60, 7000.0);
            case RUBBER -> new MaterialVoice(new double[] {1.0, 1.9, 3.1}, 95.0, 0.11, 3.5, 0.010, 0.85, 700.0);
            case PLASTIC -> new MaterialVoice(new double[] {1.0, 2.1, 3.9, 6.2}, 420.0, 0.22, 3.0, 0.004, 0.65, 2400.0);
            case COMPOSITE -> new MaterialVoice(
                    new double[] {1.0, 2.9, 5.1, 8.2}, 620.0, 0.19, 3.4, 0.003, 0.75, 5200.0);
        };
    }

    /**
     * A struck object: a broadband transient followed by decaying modes.
     *
     * @param material which voice to use
     * @param sizeFactor scales the modes down as the object gets bigger; a big panel rings lower and
     *     longer than a small bracket, which is the whole difference between a bonnet and a mirror
     * @param energy how hard it was hit, {@code (0,1]}; louder hits are also brighter, because a
     *     harder strike excites the high modes more
     * @param seed the phase and jitter seed
     */
    public static Waveform impact(AudioMaterial material, double sizeFactor, double energy, long seed) {
        MaterialVoice voice = voiceOf(material);
        double decay = voice.decaySeconds() * sizeFactor;
        Waveform wave = Waveform.ofSeconds(Math.max(0.08, decay * 1.4));
        Noise noise = new Noise(seed);

        addTransient(wave, voice.transientSeconds(), voice.transientLevel() * energy, voice.brightnessHz(), noise);
        for (int mode = 0; mode < voice.partials().length; mode++) {
            double frequency = voice.baseHz() * voice.partials()[mode] / sizeFactor;
            if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                // Above Nyquist's useful range this mode would alias into a tone that is not in the
                // model at all, which is worse than a mode that is simply absent.
                continue;
            }
            double modeDecay = decay / Math.pow(voice.decaySpread(), mode);
            // Higher modes are excited more by a harder hit and are quieter to begin with.
            double level = Math.pow(0.62, mode) * (0.55 + 0.45 * energy);
            addMode(wave, frequency, modeDecay, level, noise.nextPhase());
        }
        return wave.normalise().fadeEnds(0.002);
    }

    /**
     * A shatter: many small impacts scattered over a short window.
     *
     * <p>Modelled as a grain cloud rather than as one sound, because that is what shattering is —
     * a few hundred fragments each ringing briefly, arriving in a burst that thins out. The thinning
     * is what makes it read as glass breaking rather than as static.
     *
     * @param grains how many fragments; a windscreen is hundreds, a lamp lens is dozens
     */
    public static Waveform shatter(AudioMaterial material, int grains, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        MaterialVoice voice = voiceOf(material);

        for (int grain = 0; grain < grains; grain++) {
            // Arrival times are biased toward the start: the initial break throws most of the
            // fragments and the rest tinkle down afterwards.
            double u = noise.nextUnit();
            double at = seconds * u * u * 0.85;
            int start = (int) (at * Waveform.SAMPLE_RATE_HZ);
            double size = 0.35 + noise.nextUnit() * 1.9;
            double level = (1.0 - u * 0.8) * (0.25 + noise.nextUnit() * 0.75);
            double frequency = voice.baseHz() * (0.7 + noise.nextUnit() * 1.8) / size;
            if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                continue;
            }
            addModeAt(wave, start, frequency, voice.decaySeconds() * 0.25 * size, level * 0.35, noise.nextPhase());
        }
        return wave.normalise().fadeEnds(0.003);
    }

    /**
     * A tear: sheet metal being pulled apart.
     *
     * <p>Band-passed noise whose centre frequency sweeps downward — the sound of a crack running
     * along a panel and slowing as it goes — with a metallic ring underneath so it belongs to the
     * same object as the impacts.
     */
    public static Waveform tear(double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i) / seconds;
            double centre = 4200.0 * Math.pow(0.28, t);
            filter.set(centre, 4.0);
            // The tear is not smooth: it advances in irregular jumps, which is what the amplitude
            // roughness below is. Without it this sounds like a filter sweep, not like metal.
            double roughness = 0.55 + 0.45 * Math.abs(Math.sin(2.0 * Math.PI * 37.0 * t * seconds + noise.nextUnit()));
            double envelope = Math.pow(1.0 - t, 1.4);
            wave.add(i, (float) (filter.process(noise.nextSample()) * roughness * envelope));
        }
        MaterialVoice metal = voiceOf(AudioMaterial.METAL);
        addMode(wave, metal.baseHz() * 0.8, seconds * 0.7, 0.35, noise.nextPhase());
        addMode(wave, metal.baseHz() * 2.76 * 0.8, seconds * 0.4, 0.20, noise.nextPhase());
        return wave.normalise().fadeEnds(0.004);
    }

    /**
     * An engine loop, built from a firing frequency and its harmonics.
     *
     * <p><b>The loop is exact by construction, not by crossfade.</b> The buffer length is chosen so
     * it contains a whole number of firing cycles, which means every harmonic also completes a whole
     * number of cycles in it — so the sample after the last is exactly the first. That is the
     * property D15-R38 says generative audio cannot deliver, and it is free here because the
     * fundamental is a parameter rather than a recording.
     *
     * @param firingHz the fundamental: cylinders × rpm / 120 for a four-stroke
     * @param harmonics how many partials to stack; more is a harder, rortier engine
     * @param roughness how much cycle-to-cycle noise, {@code [0,1]}; a diesel is rough, a V12 is not
     */
    public static Waveform engineLoop(double firingHz, int harmonics, double roughness, long seed) {
        int cycles = Math.max(8, (int) Math.round(firingHz * 0.5));
        int length = (int) Math.round(cycles * Waveform.SAMPLE_RATE_HZ / firingHz);
        Waveform wave = new Waveform(length);
        Noise noise = new Noise(seed);

        double[] phases = new double[harmonics];
        for (int h = 0; h < harmonics; h++) {
            phases[h] = noise.nextPhase();
        }
        for (int i = 0; i < length; i++) {
            double cyclePosition = (double) i / length;
            double sample = 0.0;
            for (int h = 0; h < harmonics; h++) {
                double frequency = firingHz * (h + 1);
                if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                    break;
                }
                // 1/n falloff with a slight boost on the second and third, which is where an engine's
                // character lives — a pure 1/n stack sounds like a buzzer.
                double level = (h == 1 || h == 2 ? 1.35 : 1.0) / (h + 1);
                sample += level * Math.sin(2.0 * Math.PI * cycles * (h + 1) * cyclePosition + phases[h]);
            }
            // Induction and exhaust noise, modulated by the firing cycle so it pulses with it.
            double pulse = 0.5 + 0.5 * Math.sin(2.0 * Math.PI * cycles * cyclePosition);
            sample += noise.nextSample() * roughness * pulse * 0.7;
            wave.add(i, (float) sample);
        }
        // The harmonics loop exactly; the noise does not, so its seam is crossfaded away.
        return wave.loopable(0.02).normalise();
    }

    /**
     * Tyre noise: filtered noise with a tread-block rhythm.
     *
     * @param centreHz where the tread noise sits; rolling is low and broad, a skid is higher and
     *     more resonant
     * @param resonance filter Q. A skid squeals because the contact patch is resonating
     * @param blockHz how fast tread blocks pass through the contact patch
     * @param seconds loop length before the seam crossfade
     */
    public static Waveform tyreLoop(double centreHz, double resonance, double blockHz, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, resonance);

        int blockCycles = Math.max(1, (int) Math.round(blockHz * seconds));
        for (int i = 0; i < wave.length(); i++) {
            double position = (double) i / wave.length();
            double modulation = 0.72 + 0.28 * Math.sin(2.0 * Math.PI * blockCycles * position);
            wave.add(i, (float) (filter.process(noise.nextSample()) * modulation));
        }
        return wave.loopable(0.03).normalise();
    }

    /**
     * A weapon report: a pressure transient, a body, and a tail.
     *
     * @param bodyHz where the report's weight sits; a cannon is low, an autocannon is mid
     * @param crackLevel how much high-frequency crack rides on top
     * @param tailSeconds how long it rings and reflects
     */
    public static Waveform weaponReport(double bodyHz, double crackLevel, double tailSeconds, long seed) {
        Waveform wave = Waveform.ofSeconds(tailSeconds);
        Noise noise = new Noise(seed);
        BiquadBandPass body = new BiquadBandPass();
        BiquadBandPass crack = new BiquadBandPass();
        crack.set(5200.0, 1.6);

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i);
            double normalised = t / tailSeconds;
            // The body's centre falls as the pressure wave expands: a muzzle blast is a chirp
            // downward, not a static band of noise.
            body.set(bodyHz * Math.pow(0.45, normalised), 1.1);
            double envelope = Math.exp(-t * 9.0 / tailSeconds);
            double crackEnvelope = Math.exp(-t * 240.0);
            double sample = body.process(noise.nextSample()) * envelope
                    + crack.process(noise.nextSample()) * crackEnvelope * crackLevel;
            wave.add(i, (float) sample);
        }
        return wave.normalise().fadeEnds(0.002);
    }

    /**
     * A continuous weapon loop: a flamer's roar or a laser's hum.
     *
     * @param toneHz the hum's fundamental; zero for a purely noisy source like a flamer
     */
    public static Waveform weaponLoop(double toneHz, double centreHz, double resonance, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, resonance);

        int toneCycles = toneHz <= 0 ? 0 : Math.max(1, (int) Math.round(toneHz * seconds));
        for (int i = 0; i < wave.length(); i++) {
            double position = (double) i / wave.length();
            double sample = filter.process(noise.nextSample());
            if (toneCycles > 0) {
                sample = sample * 0.45 + Math.sin(2.0 * Math.PI * toneCycles * position) * 0.55;
            }
            wave.add(i, (float) sample);
        }
        return wave.loopable(0.03).normalise();
    }

    // ---- Building blocks ---------------------------------------------------------------

    /** One exponentially damped sinusoid, added over the whole buffer. */
    private static void addMode(Waveform wave, double frequency, double decaySeconds, double level, double phase) {
        addModeAt(wave, 0, frequency, decaySeconds, level, phase);
    }

    /** One damped sinusoid starting at a sample offset, for grain clouds. */
    private static void addModeAt(
            Waveform wave, int start, double frequency, double decaySeconds, double level, double phase) {
        if (start >= wave.length() || decaySeconds <= 0) {
            return;
        }
        // 60 dB of decay is where a mode stops being audible under anything else.
        double tau = decaySeconds / 6.908;
        double step = 2.0 * Math.PI * frequency / Waveform.SAMPLE_RATE_HZ;
        for (int i = start; i < wave.length(); i++) {
            double t = Waveform.timeAt(i - start);
            double envelope = Math.exp(-t / tau);
            if (envelope < 1e-4) {
                break;
            }
            wave.add(i, (float) (Math.sin(step * (i - start) + phase) * envelope * level));
        }
    }

    /** The broadband click of the strike itself: band-passed noise under a very fast decay. */
    private static void addTransient(Waveform wave, double seconds, double level, double centreHz, Noise noise) {
        int length = Math.min(wave.length(), (int) Math.round(seconds * Waveform.SAMPLE_RATE_HZ));
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, 0.8);
        for (int i = 0; i < length; i++) {
            double envelope = 1.0 - (double) i / length;
            wave.add(i, (float) (filter.process(noise.nextSample()) * envelope * envelope * level));
        }
    }

    /**
     * A seeded white-noise source.
     *
     * <p>Its own generator rather than {@code java.util.Random}, so a regenerated bank is
     * byte-identical on every JDK: {@code Random}'s algorithm is specified, but {@code nextGaussian}
     * has changed implementation between releases, and a bank whose bytes moved for that reason
     * would show up as a spurious content diff.
     */
    private static final class Noise {

        private long state;

        Noise(long seed) {
            this.state = seed * 6_364_136_223_846_793_005L + 1_442_695_040_888_963_407L;
        }

        private long next() {
            state ^= state << 13;
            state ^= state >>> 7;
            state ^= state << 17;
            return state;
        }

        /** A sample in {@code [-1, 1)}. */
        double nextSample() {
            return (next() >> 11) / (double) (1L << 52);
        }

        /** A value in {@code [0, 1)}. */
        double nextUnit() {
            return (next() >>> 11) / (double) (1L << 53);
        }

        /** A phase in {@code [0, 2π)}. */
        double nextPhase() {
            return nextUnit() * 2.0 * Math.PI;
        }
    }

    /**
     * A two-pole band-pass, in transposed direct form II.
     *
     * <p>Retunable per sample, which is what the sweeping filters above need. Recomputing the
     * coefficients every sample is not free and is a rounding error compared with everything else
     * this class does once per bank build.
     */
    private static final class BiquadBandPass {

        private double b0 = 1;
        private double b1;
        private double b2;
        private double a1;
        private double a2;
        private double z1;
        private double z2;

        void set(double centreHz, double q) {
            double omega = 2.0 * Math.PI * Math.min(centreHz, Waveform.SAMPLE_RATE_HZ * 0.45) / Waveform.SAMPLE_RATE_HZ;
            double alpha = Math.sin(omega) / (2.0 * Math.max(0.05, q));
            double cos = Math.cos(omega);
            double a0 = 1.0 + alpha;
            b0 = alpha / a0;
            b1 = 0.0;
            b2 = -alpha / a0;
            a1 = -2.0 * cos / a0;
            a2 = (1.0 - alpha) / a0;
        }

        double process(double input) {
            double output = b0 * input + z1;
            z1 = b1 * input - a1 * output + z2;
            z2 = b2 * input - a2 * output;
            return output;
        }
    }
}
