/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.pipeline.audio;

import dev.syndicate.model.AudioMaterial;
import dev.syndicate.model.EngineConfiguration;
import dev.syndicate.model.Induction;

/**
 * The synthesis primitives every sound in the bank is built from
 * (docs/15_vehicle_preparation_pipeline.md#D15-S8, D15-R38).
 *
 * <p><b>Why synthesis rather than samples.</b> D15-R38 ranks sourcing: permissively licensed
 * libraries first, procedural synthesis second, commissioned audio third — and rules generative
 * models out for loops because of the seam. Synthesis is chosen here for the whole bank, and the
 * deciding reason is the one D15-R39 raises: every audio asset has to record a licence, and the two
 * shipped car models are already CC-BY-NC-SA. Sound generated by this file carries the repository's
 * own terms and adds no second, differently-encumbered set nobody is tracking. It is also
 * reproducible — the same code produces the same bytes, so a regenerated bank is a no-op diff — and
 * it is parametric, which is what D15-S8 asks for from the engine and tyre loops anyway.
 *
 * <p><b>Impacts are modal, not noise.</b> What makes a struck object sound like metal rather than
 * like plastic is the set of frequencies it rings at, how inharmonic they are, and how long each
 * takes to decay. That is a handful of exponentially-damped sinusoids — a modal model — and it is
 * both cheaper and more convincing than filtering noise, because the ear identifies material from
 * decay time and partial spacing far more than from spectral tilt.
 *
 * <p>All randomness comes from a caller-supplied seed, so the bank is deterministic (G4's habit,
 * applied to content generation).
 */
public final class SoundSynth {

    private SoundSynth() {
        throw new AssertionError("no instances");
    }

    /**
     * The acoustic character of one material: what it rings at, and for how long.
     *
     * @param partials frequency ratios of the modes above {@link #baseHz}. Inharmonic ratios are
     *     what a struck plate or a bell has; harmonic ones sound like a string and read as musical
     * @param baseHz the lowest mode's frequency for a reference-sized object
     * @param decaySeconds how long the lowest mode takes to fall by 60 dB
     * @param decaySpread how much faster each higher mode decays; high partials always die first,
     *     which is why a struck object gets duller as it rings out
     * @param transientSeconds the length of the broadband click of the strike itself
     * @param transientLevel how loud that click is relative to the modes
     * @param brightnessHz the centre of the transient's band-pass
     */
    public record MaterialVoice(
            double[] partials,
            double baseHz,
            double decaySeconds,
            double decaySpread,
            double transientSeconds,
            double transientLevel,
            double brightnessHz) {}

    /**
     * The measured-by-ear character of each audio material.
     *
     * <p>Metal rings longest and most inharmonically; glass is short, very bright and nearly pure;
     * rubber barely rings at all and is almost entirely transient; plastic is a dull short knock;
     * composite cracks — a short bright transient over a fast-decaying low mode, which is what
     * delamination sounds like rather than the ring of a metal panel.
     */
    public static MaterialVoice voiceOf(AudioMaterial material) {
        return switch (material) {
            case METAL -> new MaterialVoice(
                    new double[] {1.0, 2.76, 5.40, 8.93, 13.34, 18.64}, 210.0, 1.60, 2.2, 0.004, 0.45, 3200.0);
            case GLASS -> new MaterialVoice(
                    new double[] {1.0, 2.32, 4.18, 6.95, 10.4}, 1850.0, 0.42, 2.8, 0.002, 0.60, 7000.0);
            case RUBBER -> new MaterialVoice(new double[] {1.0, 1.9, 3.1}, 95.0, 0.11, 3.5, 0.010, 0.85, 700.0);
            case PLASTIC -> new MaterialVoice(new double[] {1.0, 2.1, 3.9, 6.2}, 420.0, 0.22, 3.0, 0.004, 0.65, 2400.0);
            case COMPOSITE -> new MaterialVoice(
                    new double[] {1.0, 2.9, 5.1, 8.2}, 620.0, 0.19, 3.4, 0.003, 0.75, 5200.0);
        };
    }

    /**
     * A struck object: a broadband transient followed by decaying modes.
     *
     * @param material which voice to use
     * @param sizeFactor scales the modes down as the object gets bigger; a big panel rings lower and
     *     longer than a small bracket, which is the whole difference between a bonnet and a mirror
     * @param energy how hard it was hit, {@code (0,1]}; louder hits are also brighter, because a
     *     harder strike excites the high modes more
     * @param seed the phase and jitter seed
     */
    public static Waveform impact(AudioMaterial material, double sizeFactor, double energy, long seed) {
        MaterialVoice voice = voiceOf(material);
        double decay = voice.decaySeconds() * sizeFactor;
        Waveform wave = Waveform.ofSeconds(Math.max(0.08, decay * 1.4));
        Noise noise = new Noise(seed);

        addTransient(wave, voice.transientSeconds(), voice.transientLevel() * energy, voice.brightnessHz(), noise);
        for (int mode = 0; mode < voice.partials().length; mode++) {
            double frequency = voice.baseHz() * voice.partials()[mode] / sizeFactor;
            if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                // Above Nyquist's useful range this mode would alias into a tone that is not in the
                // model at all, which is worse than a mode that is simply absent.
                continue;
            }
            double modeDecay = decay / Math.pow(voice.decaySpread(), mode);
            // Higher modes are excited more by a harder hit and are quieter to begin with.
            double level = Math.pow(0.62, mode) * (0.55 + 0.45 * energy);
            addMode(wave, frequency, modeDecay, level, noise.nextPhase());
        }
        return wave.normalise().fadeEnds(0.002);
    }

    /**
     * A shatter: many small impacts scattered over a short window.
     *
     * <p>Modelled as a grain cloud rather than as one sound, because that is what shattering is —
     * a few hundred fragments each ringing briefly, arriving in a burst that thins out. The thinning
     * is what makes it read as glass breaking rather than as static.
     *
     * @param grains how many fragments; a windscreen is hundreds, a lamp lens is dozens
     */
    public static Waveform shatter(AudioMaterial material, int grains, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        MaterialVoice voice = voiceOf(material);

        for (int grain = 0; grain < grains; grain++) {
            // Arrival times are biased toward the start: the initial break throws most of the
            // fragments and the rest tinkle down afterwards.
            double u = noise.nextUnit();
            double at = seconds * u * u * 0.85;
            int start = (int) (at * Waveform.SAMPLE_RATE_HZ);
            double size = 0.35 + noise.nextUnit() * 1.9;
            double level = (1.0 - u * 0.8) * (0.25 + noise.nextUnit() * 0.75);
            double frequency = voice.baseHz() * (0.7 + noise.nextUnit() * 1.8) / size;
            if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                continue;
            }
            addModeAt(wave, start, frequency, voice.decaySeconds() * 0.25 * size, level * 0.35, noise.nextPhase());
        }
        return wave.normalise().fadeEnds(0.003);
    }

    /**
     * A tear: sheet metal being pulled apart.
     *
     * <p>Band-passed noise whose centre frequency sweeps downward — the sound of a crack running
     * along a panel and slowing as it goes — with a metallic ring underneath so it belongs to the
     * same object as the impacts.
     */
    public static Waveform tear(double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i) / seconds;
            double centre = 4200.0 * Math.pow(0.28, t);
            filter.set(centre, 4.0);
            // The tear is not smooth: it advances in irregular jumps, which is what the amplitude
            // roughness below is. Without it this sounds like a filter sweep, not like metal.
            double roughness = 0.55 + 0.45 * Math.abs(Math.sin(2.0 * Math.PI * 37.0 * t * seconds + noise.nextUnit()));
            double envelope = Math.pow(1.0 - t, 1.4);
            wave.add(i, (float) (filter.process(noise.nextSample()) * roughness * envelope));
        }
        MaterialVoice metal = voiceOf(AudioMaterial.METAL);
        addMode(wave, metal.baseHz() * 0.8, seconds * 0.7, 0.35, noise.nextPhase());
        addMode(wave, metal.baseHz() * 2.76 * 0.8, seconds * 0.4, 0.20, noise.nextPhase());
        return wave.normalise().fadeEnds(0.004);
    }

    /** Roughly how long an engine loop is, before it is rounded to a whole number of cycles. */
    public static final double ENGINE_LOOP_SECONDS = 0.48;

    /**
     * An engine loop, built as a train of exhaust pulses through a resonant exhaust.
     *
     * <p><b>An engine is not a tone generator.</b> The first cut of this method stacked harmonics of
     * the firing frequency with a 1/n falloff, which is the spectrum of a sawtooth, and it sounded
     * like one — its own comment admitted as much and boosted the second and third partials to
     * compensate. Two things are wrong with that model, and both are audible:
     *
     * <ul>
     *   <li><b>It cannot express uneven firing.</b> A harmonic stack at {@code firingHz} is by
     *       definition perfectly even, so a cross-plane V8 came out as a smooth six pitched down.
     *       Unevenness was approximated by a noise gain, which makes an engine hissier rather than
     *       lumpier — the ear locates unevenness in time, not in spectrum. Here each firing event of
     *       {@link EngineConfiguration#firingAngles()} is placed at its own crank angle and routed to
     *       its own exhaust bank, so a bank firing at {@code 90-180-180-270} produces exactly the
     *       half-order content that is a V8's burble, without anybody asking for it.
     *   <li><b>It has no formants.</b> Measured, the old loops' spectra fell monotonically with no
     *       resonant peaks anywhere. Real engine character is mostly the exhaust system: a few fixed
     *       resonances that stay put while the harmonics slide up through them as the engine revs.
     *       That is what {@link #EXHAUST_FORMANTS_HZ} is, and it is why a big engine sounds big at
     *       any rpm rather than only at low ones.
     * </ul>
     *
     * <p>The structure is therefore the physical one: a unipolar pressure pulse per firing event,
     * summed into one excitation buffer per bank, each buffer run through its own resonators. The two
     * banks of a V get slightly different formants and a small delay, because two manifolds are never
     * the same length — and it is the beat between two uneven, slightly detuned pulse trains that a
     * listener actually recognises.
     *
     * <p>The buffer holds a whole number of <em>engine cycles</em> rather than firing intervals,
     * because an uneven bank pattern repeats once per 720°. {@link Waveform#loopable(double, double)}
     * is told that cycle rate so the crossfade cannot break it.
     *
     * @param configuration which arrangement to build; supplies the firing angles and the banks
     * @param rpm the engine speed to synthesise at. The runtime pitches from here, so this must be
     *     the reference rpm the manifest records
     */
    public static Waveform engineLoop(EngineConfiguration configuration, double rpm, long seed) {
        double cycleHz = rpm / 120.0;
        double cyclePeriod = 1.0 / cycleHz;
        int cycles = Math.max(4, (int) Math.round(ENGINE_LOOP_SECONDS / cyclePeriod));
        int length = (int) Math.round(cycles * cyclePeriod * Waveform.SAMPLE_RATE_HZ);

        Noise noise = new Noise(seed);
        int bankCount = configuration.bankCount();
        double[][] excitation = new double[bankCount][length];
        double[] angles = configuration.firingAngles();
        double roughness = configuration.roughness();

        // Exhaust blowdown lasts a fraction of a firing interval: short at high cylinder counts,
        // which is part of why a V12 is smooth and an I4 is a series of separate bangs.
        double pulseSeconds = 0.34 * cyclePeriod / configuration.cylinders();
        double jitterSeconds = roughness * 0.06 * pulseSeconds;

        for (int cycle = 0; cycle < cycles; cycle++) {
            for (int i = 0; i < configuration.cylinders(); i++) {
                double at = (cycle + angles[i] / EngineConfiguration.CYCLE_DEGREES) * cyclePeriod
                        + noise.nextSample() * jitterSeconds;
                // Combustion varies cycle to cycle on any real engine, and more on a rough one.
                double level = 1.0 + noise.nextSample() * roughness * 0.30;
                addExhaustPulse(excitation[configuration.bankOf(i)], at, pulseSeconds, level, roughness, noise, true);
            }
        }

        Waveform wave = new Waveform(length);
        for (int bank = 0; bank < bankCount; bank++) {
            double divergence = bankDivergence(configuration);
            double detune = bank == 0 ? 1.0 : 1.0 - BANK_DETUNE_MAX * divergence;
            int delay = bank == 0 ? 0 : (int) Math.round(BANK_DELAY_MAX_SECONDS * divergence * Waveform.SAMPLE_RATE_HZ);
            resonate(excitation[bank], wave, configuration.cylinders(), detune, delay, 1.0 / bankCount, true);
        }
        return wave.loopable(0.02, cycleHz).normalise();
    }

    /**
     * The same engine, running at an rpm that changes over the sound — a start, a stop, an overrun.
     *
     * <p>Rather than placing pulses at known times the way {@link #engineLoop} can, this integrates
     * crank angle forward: the engine turns at whatever {@code rpmAt} says at that instant, and a
     * cylinder fires whenever the accumulated angle passes its firing angle. That is what an engine
     * does, and it is the only way the pulses stay correctly spaced while the speed is moving — a
     * cranking engine at 250 rpm and the same engine caught and idling at 850 are the same firing
     * pattern at two rates, not two different sounds.
     *
     * @param rpmAt engine speed as a function of time in seconds
     * @param levelAt how hard each firing event is, as a function of time; zero means a cylinder that
     *     does not catch, which is most of what a start sounds like
     */
    private static Waveform engineRamp(
            EngineConfiguration configuration,
            double seconds,
            java.util.function.DoubleUnaryOperator rpmAt,
            java.util.function.DoubleUnaryOperator levelAt,
            long seed) {

        int length = (int) Math.round(seconds * Waveform.SAMPLE_RATE_HZ);
        Noise noise = new Noise(seed);
        int bankCount = configuration.bankCount();
        double[][] excitation = new double[bankCount][length];
        double[] angles = configuration.firingAngles();
        double roughness = configuration.roughness();

        double angle = 0.0;
        int event = 0;
        double nextAngle = angles[0];
        for (int i = 0; i < length; i++) {
            double t = Waveform.timeAt(i);
            double rpm = Math.max(0.0, rpmAt.applyAsDouble(t));
            // Degrees per sample: rpm × 360 / 60 / sampleRate.
            angle += rpm * 6.0 / Waveform.SAMPLE_RATE_HZ;
            while (angle >= nextAngle) {
                double level = levelAt.applyAsDouble(t);
                if (level > 0.001 && rpm > 1.0) {
                    // Pulse width follows the firing interval, so a slow-turning engine's pulses are
                    // long and soft and a revving one's are short and hard.
                    double pulseSeconds = 0.34 * (120.0 / Math.max(60.0, rpm)) / configuration.cylinders();
                    addExhaustPulse(
                            excitation[configuration.bankOf(event)],
                            t,
                            pulseSeconds,
                            level * (1.0 + noise.nextSample() * roughness * 0.30),
                            roughness,
                            noise,
                            false);
                }
                event++;
                nextAngle = angles[event % configuration.cylinders()]
                        + EngineConfiguration.CYCLE_DEGREES * (event / configuration.cylinders());
            }
        }

        Waveform wave = new Waveform(length);
        for (int bank = 0; bank < bankCount; bank++) {
            double divergence = bankDivergence(configuration);
            double detune = bank == 0 ? 1.0 : 1.0 - BANK_DETUNE_MAX * divergence;
            int delay = bank == 0 ? 0 : (int) Math.round(BANK_DELAY_MAX_SECONDS * divergence * Waveform.SAMPLE_RATE_HZ);
            resonate(excitation[bank], wave, configuration.cylinders(), detune, delay, 1.0 / bankCount, false);
        }
        return wave;
    }

    /**
     * Ignition: a starter motor turning a cold engine, the catch, and the flare down to idle.
     *
     * <p>Three phases, and the middle one is the whole sound. A starter spins the engine at a few
     * hundred rpm with nothing firing — that is the whirr — and then cylinders begin to catch, one at
     * a time and unevenly, before the engine picks itself up and overshoots idle. Rendering it as a
     * ramp through {@link #engineRamp} rather than as a canned noise means the catch is the same
     * firing pattern the loop uses, so a V8 starts like a V8.
     */
    public static Waveform engineStart(EngineConfiguration configuration, double idleRpm, long seed) {
        double crankSeconds = 0.62;
        double catchSeconds = 0.30;
        double seconds = 1.75;
        double crankRpm = 260.0;
        double flareRpm = idleRpm * 1.45;

        Waveform wave = engineRamp(
                configuration,
                seconds,
                t -> {
                    if (t < crankSeconds) {
                        // The starter labours slightly as compression comes round.
                        return crankRpm * (0.88 + 0.12 * Math.sin(2.0 * Math.PI * 6.0 * t));
                    }
                    if (t < crankSeconds + catchSeconds) {
                        return crankRpm + (flareRpm - crankRpm) * ((t - crankSeconds) / catchSeconds);
                    }
                    double settle = (t - crankSeconds - catchSeconds) / (seconds - crankSeconds - catchSeconds);
                    return flareRpm + (idleRpm - flareRpm) * Math.min(1.0, settle * 1.6);
                },
                t -> {
                    if (t < crankSeconds * 0.72) {
                        return 0.0;
                    }
                    if (t < crankSeconds) {
                        // The first cylinders to catch fire weakly and not every time round.
                        return 0.35 * ((t - crankSeconds * 0.72) / (crankSeconds * 0.28));
                    }
                    return 1.0;
                },
                seed);

        addStarterMotor(wave, crankSeconds, new Noise(seed ^ 0x57A27E5L));
        return wave.normalise().fadeEnds(0.004);
    }

    /**
     * Shutdown: fuel cuts, the last charges burn, and the engine rocks to a halt on compression.
     *
     * <p>The tail is the recognisable part. An engine does not coast smoothly to zero — it slows, and
     * the last compression stroke it cannot get over pushes it back, which is the little mechanical
     * knock at the end.
     */
    public static Waveform engineStop(EngineConfiguration configuration, double idleRpm, long seed) {
        double seconds = 1.15;
        double fuelCut = 0.26;

        Waveform wave = engineRamp(
                configuration,
                seconds,
                t -> idleRpm * Math.max(0.0, Math.pow(1.0 - t / (seconds * 0.85), 1.7)),
                t -> t < fuelCut ? 1.0 - t / fuelCut : 0.0,
                seed);

        // The rock-back: a dull knock as the crank fails to clear its last compression.
        MaterialVoice metal = voiceOf(AudioMaterial.METAL);
        int at = (int) Math.round(seconds * 0.80 * Waveform.SAMPLE_RATE_HZ);
        addModeAt(wave, at, metal.baseHz() * 0.42, 0.09, 0.30, 0.0);
        addModeAt(wave, at, metal.baseHz() * 1.13, 0.05, 0.16, 1.1);
        return wave.normalise().fadeEnds(0.004);
    }

    /**
     * Off-throttle overrun: the exhaust popping and crackling as the driver lifts.
     *
     * <p>Closed throttle means weak, irregular firing — so the pulse train drops to a fraction of its
     * level — over which unburnt fuel lights in the hot exhaust. Those pops are the sound, and they
     * are deliberately irregular: a periodic crackle reads as a machine gun rather than as a car.
     */
    public static Waveform engineOverrun(EngineConfiguration configuration, double rpm, long seed) {
        double seconds = 1.20;
        Waveform wave = engineRamp(
                configuration,
                seconds,
                t -> rpm * (1.0 - 0.42 * (t / seconds)),
                t -> 0.30 * (1.0 - 0.5 * (t / seconds)),
                seed);

        Noise noise = new Noise(seed ^ 0x90F5L);
        int pops = 9 + (int) (noise.nextUnit() * 7);
        for (int pop = 0; pop < pops; pop++) {
            double at = noise.nextUnit() * seconds * 0.92;
            double level = 0.28 + noise.nextUnit() * 0.72;
            addCrackle(wave, at, 1400.0 + noise.nextUnit() * 2600.0, 0.055, level, noise);
        }
        return wave.normalise().fadeEnds(0.004);
    }

    /**
     * The second voice of a forced-induction engine: a supercharger's whine or a turbo's rush.
     *
     * <p>The two are not the same sound at two settings, and the reason is mechanical. A
     * positive-displacement blower is <em>geared to the crank</em>, so it produces a hard tone at a
     * fixed order of engine speed with strong harmonics — the note a listener identifies a
     * supercharged car by before the exhaust registers at all. A turbo is spun by exhaust flow, so it
     * is mostly broadband rush with only a weak tone in it. {@link Induction#tonality()} is the single
     * parameter that separates them, and it is why one file per member is enough.
     *
     * @param rpm the engine speed to synthesise at; the runtime pitches from here
     */
    public static Waveform inductionLoop(Induction induction, double rpm, long seed) {
        if (!induction.isForced()) {
            throw new IllegalArgumentException("naturally aspirated engines have no induction voice");
        }
        double fundamental = rpm / 60.0 * induction.driveRatio();
        int cycles = Math.max(8, (int) Math.round(fundamental * 0.40));
        int length = (int) Math.round(cycles * Waveform.SAMPLE_RATE_HZ / fundamental);

        Waveform wave = new Waveform(length);
        Noise noise = new Noise(seed);
        BiquadBandPass rush = new BiquadBandPass();
        // A blower's rush is broad and sits under its tone; a turbo's is narrow and is the whole
        // sound, which is what makes it read as air rather than as machinery.
        rush.set(fundamental * (induction.tonality() > 0.5 ? 2.2 : 1.0), induction.tonality() > 0.5 ? 1.2 : 6.0);

        int partials = induction.tonality() > 0.5 ? 4 : 2;
        double[] phases = new double[partials];
        for (int p = 0; p < partials; p++) {
            phases[p] = noise.nextPhase();
        }

        for (int i = 0; i < length; i++) {
            double position = (double) i / length;
            double tone = 0.0;
            for (int p = 0; p < partials; p++) {
                double frequency = fundamental * (p + 1);
                if (frequency >= Waveform.SAMPLE_RATE_HZ * 0.45) {
                    break;
                }
                // A screw blower's harmonics fall slowly, which is what makes the whine cut through
                // an exhaust note rather than sitting behind it.
                tone += Math.sin(2.0 * Math.PI * cycles * (p + 1) * position + phases[p]) / Math.pow(p + 1, 0.7);
            }
            double air = rush.process(noise.nextSample());
            wave.add(i, (float) (tone * induction.tonality() + air * (1.0 - induction.tonality()) * 1.8));
        }
        // A longer crossfade than an engine loop gets, because an induction voice is mostly air: a
        // turbo at 0.35 tonality is broadband noise around 5 kHz, where adjacent samples differ so
        // much that a 20 ms fade leaves a join no smoother than the buffer's own texture. Rounding to
        // whole cycles still applies, so the tone underneath stays phase-continuous.
        return wave.loopable(INDUCTION_CROSSFADE_SECONDS, fundamental).normalise();
    }

    /** Crossfade for an induction loop. Longer than an engine's, because the content is noisier. */
    private static final double INDUCTION_CROSSFADE_SECONDS = 0.05;

    /**
     * A turbo letting go when the driver lifts: the blow-off valve and the flutter behind it.
     *
     * <p>A downward-sweeping band of noise, because the trapped charge escapes and the pressure
     * behind it falls as it goes, with a fast tremolo over the top — the flutter of a compressor
     * surging against a closed throttle.
     */
    public static Waveform inductionRelease(long seed) {
        double seconds = 0.42;
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i);
            double u = t / seconds;
            filter.set(3600.0 * Math.pow(0.19, u), 2.6);
            double envelope = Math.pow(1.0 - u, 1.5);
            double flutter = 0.72 + 0.28 * Math.sin(2.0 * Math.PI * 24.0 * t) * (1.0 - u);
            wave.add(i, (float) (filter.process(noise.nextSample()) * envelope * flutter));
        }
        return wave.normalise().fadeEnds(0.004);
    }

    /**
     * A vehicle burning: the roar of the fire and the crackle in it.
     *
     * <p>Two uncorrelated layers, because that is what fire is — a broad low rush that swells and
     * falls at a rate too slow to hear as pitch, and sharp irregular cracks scattered over it. The
     * swell is deliberately slow and aperiodic: a fire loop whose modulation is regular is
     * immediately identifiable as a loop, which matters here more than anywhere else in the bank
     * because a burning car burns for as long as it takes somebody to finish it off.
     */
    public static Waveform fireLoop(double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass body = new BiquadBandPass();
        BiquadBandPass breath = new BiquadBandPass();
        breath.set(1750.0, 0.8);

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i);
            // Three slow swells at incommensurate rates, so the sum never repeats within the loop.
            double swell = 0.62
                    + 0.16 * Math.sin(2.0 * Math.PI * 0.7 * t)
                    + 0.13 * Math.sin(2.0 * Math.PI * 1.13 * t + 1.7)
                    + 0.09 * Math.sin(2.0 * Math.PI * 1.91 * t + 4.1);
            body.set(300.0 + 90.0 * swell, 0.7);
            double sample = body.process(noise.nextSample()) * swell + breath.process(noise.nextSample()) * 0.22;
            wave.add(i, (float) sample);
        }

        int cracks = (int) Math.round(seconds * 14);
        for (int crack = 0; crack < cracks; crack++) {
            addCrackle(
                    wave,
                    noise.nextUnit() * seconds * 0.97,
                    900.0 + noise.nextUnit() * 3200.0,
                    0.022,
                    0.18 + noise.nextUnit() * 0.5,
                    noise);
        }
        return wave.loopable(0.06).normalise();
    }

    /** A starter motor: a low armature whirr with the gear whine riding on it, fading at the catch. */
    private static void addStarterMotor(Waveform wave, double crankSeconds, Noise noise) {
        double phase = noise.nextPhase();
        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i);
            if (t > crankSeconds * 1.12) {
                break;
            }
            // Fades over the last eighth rather than cutting: a starter disengages, it does not stop.
            double envelope = t < crankSeconds ? 1.0 : 1.0 - (t - crankSeconds) / (crankSeconds * 0.12);
            double armature = Math.sin(2.0 * Math.PI * 88.0 * t + phase);
            double gear = Math.sin(2.0 * Math.PI * 1160.0 * t) * 0.30;
            double grind = noise.nextSample() * 0.22;
            wave.add(i, (float) ((armature * 0.34 + gear + grind) * envelope * 0.42));
        }
    }

    /** One short bright crack: a band-passed click under a very fast decay. */
    private static void addCrackle(
            Waveform wave, double atSeconds, double centreHz, double seconds, double level, Noise noise) {

        int start = (int) Math.round(atSeconds * Waveform.SAMPLE_RATE_HZ);
        int span = Math.max(2, (int) Math.round(seconds * Waveform.SAMPLE_RATE_HZ));
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, 2.2);
        for (int i = 0; i < span; i++) {
            int at = start + i;
            if (at >= wave.length()) {
                break;
            }
            double envelope = Math.exp(-(double) i / span * 5.5);
            wave.add(at, (float) (filter.process(noise.nextSample()) * envelope * level));
        }
    }

    /** The most a second bank's exhaust is detuned from the first's. See {@link #bankDivergence}. */
    private static final double BANK_DETUNE_MAX = 0.06;

    /** The most a second bank's manifold can lag the first's. See {@link #bankDivergence}. */
    private static final double BANK_DELAY_MAX_SECONDS = 0.0014;

    /** How matched a pair of banks is when they fire identically. Never zero: nothing is identical. */
    private static final double BANK_DIVERGENCE_MIN = 0.10;

    /**
     * How far apart to hold a V's two exhaust banks, from how differently they fire.
     *
     * <p><b>This is the parameter the burble actually lives in, and finding that out took two wrong
     * answers.</b> The arithmetic is worth writing down, because it is not what it looks like.
     *
     * <p>A cross-plane V8's banks fire at {@code 180-270-180-90} and {@code 180-90-180-270} — one is
     * the other reversed. Reversing a pulse train conjugates its spectrum, and when the two are
     * summed *perfectly* the odd orders cancel to exactly zero: a cross-plane V8 with ideally matched,
     * ideally merged exhausts fires evenly every 90° and has no burble at all. That is not a modelling
     * artefact, it is why fitting an X-pipe to one audibly flattens it out. So the burble is not
     * produced by the uneven bank pattern alone — it is produced by that pattern <em>failing to
     * cancel</em>, and what stops it cancelling is the two banks reaching the listener differently.
     *
     * <p>Which is why the first attempt at this was wrong in both directions. It applied a large fixed
     * divergence to every V, so the even-firing V6 and V10 — whose banks fire identically and should
     * therefore stay even — came out with *more* off-firing-order energy than the V8 did. Halving it
     * to a physically plausible 0.3 ms then cancelled the V8's odd orders almost completely and left
     * the arrangement with a single weak line, no richer than a V6's.
     *
     * <p>The resolution is that divergence is not a global constant: it scales with how differently
     * the two banks fire. Banks that fire identically are held nearly matched, so an even-firing V
     * keeps one faint sub-order line — a real V6 does have a slight offbeat — while the cross-plane
     * V8's banks are allowed to diverge fully and its orders 3, 5 and 7 come through. Measured, that
     * is four sub-firing-order lines against one, which is the difference between a burble and an
     * offbeat.
     */
    private static double bankDivergence(EngineConfiguration configuration) {
        double unevenness = Math.min(1.0, configuration.bankFiringSpreadDegrees() / 180.0);
        return BANK_DIVERGENCE_MIN + (1.0 - BANK_DIVERGENCE_MIN) * unevenness;
    }

    /**
     * The exhaust's fixed resonances, in Hz, for a reference eight-cylinder engine.
     *
     * <p>Three peaks: the main pipe, the mid-body that carries most of the character, and the rasp.
     * They are scaled by {@link #formantScale} for other cylinder counts, so a twelve sits lower and
     * a four higher — which is the difference between an engine sounding big and sounding loud.
     */
    public static final double[] EXHAUST_FORMANTS_HZ = {105.0, 560.0, 1750.0};

    /** How sharp each formant is. The low pipe resonance is the most selective. */
    private static final double[] EXHAUST_FORMANT_Q = {8.0, 4.0, 2.5};

    /** Relative weight of each formant in the sum. */
    private static final double[] EXHAUST_FORMANT_GAIN = {1.0, 0.62, 0.26};

    /**
     * How far an engine's formants move from the eight-cylinder reference.
     *
     * <p>A bigger engine has a bigger exhaust, and a bigger pipe resonates lower. Exponent 0.35
     * rather than 1.0 because pipe resonance goes with length, and length grows far more slowly than
     * cylinder count — a V12's exhaust is not half again as long as a V8's.
     */
    private static double formantScale(int cylinders) {
        return Math.pow(8.0 / cylinders, 0.35);
    }

    /**
     * One exhaust blowdown: a fast rise and an exponential fall, wrapped around the buffer.
     *
     * <p>Unipolar, because exhaust pressure is — it pushes and never pulls. The resonators downstream
     * remove the DC, but the asymmetry is what gives them something with real low-frequency energy to
     * ring on; a symmetric pulse produces a thinner engine.
     *
     * <p>Wrapping rather than clipping at the buffer end is what makes the train genuinely periodic:
     * a pulse that starts 2 ms before the end continues into the first 2 ms, which is exactly what
     * the next repetition of the loop would do.
     */
    private static void addExhaustPulse(
            double[] buffer,
            double atSeconds,
            double pulseSeconds,
            double level,
            double roughness,
            Noise noise,
            boolean wrap) {

        int length = buffer.length;
        int start = (int) Math.round(atSeconds * Waveform.SAMPLE_RATE_HZ);
        int span = Math.max(2, (int) Math.round(pulseSeconds * Waveform.SAMPLE_RATE_HZ));
        double rise = 0.18;

        for (int i = 0; i < span; i++) {
            int at = start + i;
            if (wrap) {
                at = Math.floorMod(at, length);
            } else if (at < 0 || at >= length) {
                continue;
            }
            double u = (double) i / span;
            double envelope = u < rise ? u / rise : Math.exp(-(u - rise) / (1.0 - rise) * 3.6);
            // Turbulence in the port. Scaled by the envelope so it belongs to the pulse rather than
            // sitting under the whole loop as a hiss.
            double turbulence = noise.nextSample() * roughness * 0.45;
            buffer[at] += level * envelope * (1.0 + turbulence);
        }
    }

    /**
     * Runs one bank's excitation through the exhaust formants and sums it into the output.
     *
     * @param detune multiplies this bank's formant frequencies; 1.0 for the first bank
     * @param delaySamples how much later this bank's manifold delivers
     * @param wrap whether the delay wraps around the buffer, which it must for a loop and must not
     *     for a one-shot
     */
    private static void resonate(
            double[] excitation,
            Waveform out,
            int cylinders,
            double detune,
            int delaySamples,
            double gain,
            boolean wrap) {

        double scale = formantScale(cylinders) * detune;
        for (int formant = 0; formant < EXHAUST_FORMANTS_HZ.length; formant++) {
            BiquadBandPass filter = new BiquadBandPass();
            filter.set(EXHAUST_FORMANTS_HZ[formant] * scale, EXHAUST_FORMANT_Q[formant]);
            double weight = EXHAUST_FORMANT_GAIN[formant] * gain;
            for (int i = 0; i < excitation.length; i++) {
                double value = filter.process(excitation[i]) * weight;
                int at = i + delaySamples;
                if (wrap) {
                    at = Math.floorMod(at, excitation.length);
                } else if (at >= excitation.length) {
                    continue;
                }
                out.add(at, (float) value);
            }
        }
    }

    /**
     * Tyre noise: filtered noise with a tread-block rhythm.
     *
     * @param centreHz where the tread noise sits; rolling is low and broad, a skid is higher and
     *     more resonant
     * @param resonance filter Q. A skid squeals because the contact patch is resonating
     * @param blockHz how fast tread blocks pass through the contact patch
     * @param seconds loop length before the seam crossfade
     */
    public static Waveform tyreLoop(double centreHz, double resonance, double blockHz, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, resonance);

        int blockCycles = Math.max(1, (int) Math.round(blockHz * seconds));
        for (int i = 0; i < wave.length(); i++) {
            double position = (double) i / wave.length();
            double modulation = 0.72 + 0.28 * Math.sin(2.0 * Math.PI * blockCycles * position);
            wave.add(i, (float) (filter.process(noise.nextSample()) * modulation));
        }
        return wave.loopable(0.03).normalise();
    }

    /**
     * A weapon report: a pressure transient, a body, and a tail.
     *
     * @param bodyHz where the report's weight sits; a cannon is low, an autocannon is mid
     * @param crackLevel how much high-frequency crack rides on top
     * @param tailSeconds how long it rings and reflects
     */
    public static Waveform weaponReport(double bodyHz, double crackLevel, double tailSeconds, long seed) {
        Waveform wave = Waveform.ofSeconds(tailSeconds);
        Noise noise = new Noise(seed);
        BiquadBandPass body = new BiquadBandPass();
        BiquadBandPass crack = new BiquadBandPass();
        crack.set(5200.0, 1.6);

        for (int i = 0; i < wave.length(); i++) {
            double t = Waveform.timeAt(i);
            double normalised = t / tailSeconds;
            // The body's centre falls as the pressure wave expands: a muzzle blast is a chirp
            // downward, not a static band of noise.
            body.set(bodyHz * Math.pow(0.45, normalised), 1.1);
            double envelope = Math.exp(-t * 9.0 / tailSeconds);
            double crackEnvelope = Math.exp(-t * 240.0);
            double sample = body.process(noise.nextSample()) * envelope
                    + crack.process(noise.nextSample()) * crackEnvelope * crackLevel;
            wave.add(i, (float) sample);
        }
        return wave.normalise().fadeEnds(0.002);
    }

    /**
     * A continuous weapon loop: a flamer's roar or a laser's hum.
     *
     * @param toneHz the hum's fundamental; zero for a purely noisy source like a flamer
     */
    public static Waveform weaponLoop(double toneHz, double centreHz, double resonance, double seconds, long seed) {
        Waveform wave = Waveform.ofSeconds(seconds);
        Noise noise = new Noise(seed);
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, resonance);

        int toneCycles = toneHz <= 0 ? 0 : Math.max(1, (int) Math.round(toneHz * seconds));
        for (int i = 0; i < wave.length(); i++) {
            double position = (double) i / wave.length();
            double sample = filter.process(noise.nextSample());
            if (toneCycles > 0) {
                sample = sample * 0.45 + Math.sin(2.0 * Math.PI * toneCycles * position) * 0.55;
            }
            wave.add(i, (float) sample);
        }
        return wave.loopable(0.03).normalise();
    }

    // ---- Building blocks ---------------------------------------------------------------

    /** One exponentially damped sinusoid, added over the whole buffer. */
    private static void addMode(Waveform wave, double frequency, double decaySeconds, double level, double phase) {
        addModeAt(wave, 0, frequency, decaySeconds, level, phase);
    }

    /** One damped sinusoid starting at a sample offset, for grain clouds. */
    private static void addModeAt(
            Waveform wave, int start, double frequency, double decaySeconds, double level, double phase) {
        if (start >= wave.length() || decaySeconds <= 0) {
            return;
        }
        // 60 dB of decay is where a mode stops being audible under anything else.
        double tau = decaySeconds / 6.908;
        double step = 2.0 * Math.PI * frequency / Waveform.SAMPLE_RATE_HZ;
        for (int i = start; i < wave.length(); i++) {
            double t = Waveform.timeAt(i - start);
            double envelope = Math.exp(-t / tau);
            if (envelope < 1e-4) {
                break;
            }
            wave.add(i, (float) (Math.sin(step * (i - start) + phase) * envelope * level));
        }
    }

    /** The broadband click of the strike itself: band-passed noise under a very fast decay. */
    private static void addTransient(Waveform wave, double seconds, double level, double centreHz, Noise noise) {
        int length = Math.min(wave.length(), (int) Math.round(seconds * Waveform.SAMPLE_RATE_HZ));
        BiquadBandPass filter = new BiquadBandPass();
        filter.set(centreHz, 0.8);
        for (int i = 0; i < length; i++) {
            double envelope = 1.0 - (double) i / length;
            wave.add(i, (float) (filter.process(noise.nextSample()) * envelope * envelope * level));
        }
    }

    /**
     * A seeded white-noise source.
     *
     * <p>Its own generator rather than {@code java.util.Random}, so a regenerated bank is
     * byte-identical on every JDK: {@code Random}'s algorithm is specified, but {@code nextGaussian}
     * has changed implementation between releases, and a bank whose bytes moved for that reason
     * would show up as a spurious content diff.
     */
    private static final class Noise {

        private long state;

        Noise(long seed) {
            this.state = seed * 6_364_136_223_846_793_005L + 1_442_695_040_888_963_407L;
        }

        private long next() {
            state ^= state << 13;
            state ^= state >>> 7;
            state ^= state << 17;
            return state;
        }

        /** A sample in {@code [-1, 1)}. */
        double nextSample() {
            return (next() >> 11) / (double) (1L << 52);
        }

        /** A value in {@code [0, 1)}. */
        double nextUnit() {
            return (next() >>> 11) / (double) (1L << 53);
        }

        /** A phase in {@code [0, 2π)}. */
        double nextPhase() {
            return nextUnit() * 2.0 * Math.PI;
        }
    }

    /**
     * A two-pole band-pass, in transposed direct form II.
     *
     * <p>Retunable per sample, which is what the sweeping filters above need. Recomputing the
     * coefficients every sample is not free and is a rounding error compared with everything else
     * this class does once per bank build.
     */
    private static final class BiquadBandPass {

        private double b0 = 1;
        private double b1;
        private double b2;
        private double a1;
        private double a2;
        private double z1;
        private double z2;

        void set(double centreHz, double q) {
            double omega = 2.0 * Math.PI * Math.min(centreHz, Waveform.SAMPLE_RATE_HZ * 0.45) / Waveform.SAMPLE_RATE_HZ;
            double alpha = Math.sin(omega) / (2.0 * Math.max(0.05, q));
            double cos = Math.cos(omega);
            double a0 = 1.0 + alpha;
            b0 = alpha / a0;
            b1 = 0.0;
            b2 = -alpha / a0;
            a1 = -2.0 * cos / a0;
            a2 = (1.0 - alpha) / a0;
        }

        double process(double input) {
            double output = b0 * input + z1;
            z1 = b1 * input - a1 * output + z2;
            z2 = b2 * input - a2 * output;
            return output;
        }
    }
}
