/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.pipeline.audio;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.syndicate.model.AudioEvent;
import dev.syndicate.model.AudioMaterial;
import dev.syndicate.model.DestructionClass;
import dev.syndicate.model.WeaponFamily;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Generates the whole sound bank of D15-S8 into {@code assets/audio/}
 * (docs/15_vehicle_preparation_pipeline.md#D15-S8, D15-R36 to D15-R39).
 *
 * <p><b>The inventory is per class and per material, never per vehicle</b> (D15-R37). That is what
 * keeps it at this size: seven event families over five audio materials, four destruction classes,
 * three surfaces and seven weapon families comes to a few dozen files, and adding a tenth car to the
 * roster adds none of them.
 *
 * <p><b>No engine sounds live here any more</b> (DEC-056). They are synthesised in the client as the
 * car runs, because an engine is the one thing in the bank whose state the player changes
 * continuously — and a file cannot drop a cylinder, lose an exhaust, or be started and stopped
 * without becoming three more files.
 *
 * <p><b>Everything is synthesised, and the licence is the point.</b> D15-R39 requires every audio
 * asset to record its licence, and the two shipped car models are already CC-BY-NC-SA — a constraint
 * that is live and that nobody wants a second, differently-encumbered version of. Sound generated by
 * this class carries the repository's own terms. It is also reproducible: regenerating the bank
 * produces byte-identical files, so a rebuild is a no-op diff rather than a review of forty binaries.
 *
 * <p>{@code audio.json} beside the files is the manifest the runtime reads: which asset answers
 * which {@code (event, key)} pair, whether it loops, and what its reference parameters were.
 */
public final class SoundBankBuilder {

    /** Where the bank lives under the asset root. */
    public static final String AUDIO_DIRECTORY = "audio";

    /** The manifest's file name. */
    public static final String MANIFEST_FILE = "audio.json";

    /**
     * The seed every sound's noise derives from.
     *
     * <p>Fixed, and each sound offsets it by a hash of its own id, so regenerating one file does not
     * move any other and the whole bank is reproducible from this one number.
     */
    public static final long BANK_SEED = 0x5D1CA7EDL;

    /**
     * The engine is no longer in this bank.
     *
     * <p>Six loops, eighteen start / stop / overrun one-shots and three induction files — 27 of the
     * 74 this builder used to write — are now {@code EngineSynth} in {@code game-client}, synthesised
     * as the car runs (DEC-056, D15-R37a3). None of them could express a dropped cylinder or a torn
     * exhaust, and the twelve transients existed only because a loop cannot change speed.
     *
     * <p>What is left is everything a file is genuinely better at: impacts, shatters, debris, tyres,
     * weapons and fire, all of which are events or textures rather than a machine whose state the
     * player is continuously changing.
     */
    /** How long the fire loop is. Long enough that its aperiodic swells do not read as a cycle. */
    public static final double FIRE_LOOP_SECONDS = 2.4;

    /** Surfaces a tyre loop is authored for. */
    public static final List<String> SURFACES = List.of("tarmac", "gravel", "metal");

    private final Path audioRoot;
    private final ObjectMapper mapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    private final List<ObjectNode> entries = new ArrayList<>();

    public SoundBankBuilder(Path assetRoot) {
        this.audioRoot = assetRoot.resolve(AUDIO_DIRECTORY);
    }

    /**
     * Writes every sound and the manifest.
     *
     * @return how many audio files were written
     */
    public int build() throws IOException {
        entries.clear();
        Files.createDirectories(audioRoot);

        buildImpacts();
        buildDetaches();
        buildShatters();
        buildDebrisSettles();
        buildFire();
        buildTyres();
        buildWeapons();

        writeManifest();
        writeLicence();
        return entries.size();
    }

    // ---- Impacts (per material, by impulse) --------------------------------------------

    /**
     * Three severities per material, so the runtime can pick by impulse rather than pitch one sound.
     *
     * <p>Severity is not volume. A hard hit on steel rings lower, longer and brighter than a light
     * one, because a bigger area of the panel is excited — pitching one recording up and down gives
     * a chipmunk, which is the single most recognisable sign of a cheap sound bank.
     */
    private void buildImpacts() throws IOException {
        record Severity(String name, double sizeFactor, double energy) {}
        List<Severity> severities = List.of(
                new Severity("light", 0.55, 0.35), new Severity("medium", 1.0, 0.7), new Severity("heavy", 1.9, 1.0));

        for (AudioMaterial material : AudioMaterial.values()) {
            for (Severity severity : severities) {
                String id = "impact_" + material.token() + "_" + severity.name();
                Waveform wave = SoundSynth.impact(material, severity.sizeFactor(), severity.energy(), seedFor(id));
                write(id, wave, AudioEvent.IMPACT, material.name() + ":" + severity.name(), false, node -> {
                    node.put("audioMaterial", material.name());
                    node.put("severity", severity.name());
                });
            }
        }
    }

    // ---- Part detachment (per destruction class) ---------------------------------------

    /**
     * One sound per destruction class (D15-S8: {@code sheet_metal} tears, {@code glass} shatters,
     * {@code rigid} clangs).
     *
     * <p>{@code NONE} gets no file, which is the class doing its job: a decal riding its host is not
     * an event, and generating a silent asset for it would be a file somebody later wonders about.
     */
    private void buildDetaches() throws IOException {
        for (DestructionClass destructionClass : DestructionClass.values()) {
            if (destructionClass == DestructionClass.NONE) {
                continue;
            }
            String id = "part_detach_" + destructionClass.name().toLowerCase(Locale.ROOT);
            long seed = seedFor(id);
            Waveform wave =
                    switch (destructionClass) {
                        case SHEET_METAL -> SoundSynth.tear(0.55, seed);
                        case GLASS -> SoundSynth.shatter(AudioMaterial.GLASS, 180, 0.9, seed);
                        case STRUCTURAL -> SoundSynth.tear(1.1, seed);
                        case RIGID -> SoundSynth.impact(AudioMaterial.METAL, 1.5, 0.9, seed);
                        case NONE -> throw new IllegalStateException("filtered above");
                    };
            write(
                    id,
                    wave,
                    AudioEvent.PART_DETACH,
                    destructionClass.name(),
                    false,
                    node -> node.put("destructionClass", destructionClass.name()));
        }
    }

    // ---- Glass ---------------------------------------------------------------------------

    /** A windscreen and a lamp lens are the same material and very different amounts of it. */
    private void buildShatters() throws IOException {
        record Pane(String name, int grains, double seconds) {}
        for (Pane pane : List.of(new Pane("large", 320, 1.4), new Pane("small", 70, 0.6))) {
            String id = "glass_shatter_" + pane.name();
            Waveform wave = SoundSynth.shatter(AudioMaterial.GLASS, pane.grains(), pane.seconds(), seedFor(id));
            write(id, wave, AudioEvent.GLASS_SHATTER, pane.name(), false, node -> node.put("pane", pane.name()));
        }
    }

    // ---- Debris ---------------------------------------------------------------------------

    /** A shard coming to rest: a small impact, quieter and duller than the one that made it. */
    private void buildDebrisSettles() throws IOException {
        for (AudioMaterial material : AudioMaterial.values()) {
            String id = "debris_settle_" + material.token();
            Waveform wave = SoundSynth.impact(material, 0.4, 0.28, seedFor(id));
            write(
                    id,
                    wave,
                    AudioEvent.DEBRIS_SETTLE,
                    material.name(),
                    false,
                    node -> node.put("audioMaterial", material.name()));
        }
    }

    /** One fire loop. A burning car burns the same way whatever it is made of. */
    private void buildFire() throws IOException {
        String id = "fire_loop";
        write(
                id,
                SoundSynth.fireLoop(FIRE_LOOP_SECONDS, seedFor(id)),
                AudioEvent.FIRE_LOOP,
                "DEFAULT",
                true,
                node -> node.put("seconds", FIRE_LOOP_SECONDS));
    }

    // ---- Tyres -----------------------------------------------------------------------------

    private void buildTyres() throws IOException {
        record Surface(String name, double rollHz, double rollQ, double skidHz, double skidQ) {}
        List<Surface> surfaces = List.of(
                new Surface("tarmac", 900.0, 0.8, 1650.0, 5.5),
                new Surface("gravel", 1400.0, 0.5, 1200.0, 1.4),
                new Surface("metal", 1800.0, 1.4, 2600.0, 7.0));

        for (Surface surface : surfaces) {
            String rollId = "tyre_roll_" + surface.name();
            Waveform roll = SoundSynth.tyreLoop(surface.rollHz(), surface.rollQ(), 46.0, 0.9, seedFor(rollId));
            write(
                    rollId,
                    roll,
                    AudioEvent.TYRE_ROLL,
                    surface.name(),
                    true,
                    node -> node.put("surface", surface.name()));

            String skidId = "tyre_skid_" + surface.name();
            // A skid's tread rhythm is slower and its filter far more resonant: the squeal is the
            // contact patch ringing, which is exactly what a high Q is.
            Waveform skid = SoundSynth.tyreLoop(surface.skidHz(), surface.skidQ(), 18.0, 0.9, seedFor(skidId));
            write(
                    skidId,
                    skid,
                    AudioEvent.TYRE_SKID,
                    surface.name(),
                    true,
                    node -> node.put("surface", surface.name()));
        }
    }

    // ---- Weapons -----------------------------------------------------------------------------

    /**
     * A fire and an impact per family (D01-R8: eight families, eight pairs).
     *
     * <p>The two continuous families are loops rather than one-shots, because a flamer and a laser
     * are held down. {@code RAM} gets neither: its "fire" is a collision, which the impact bank
     * already covers, and generating a duplicate under a second id is how two sounds end up playing
     * for one event.
     */
    private void buildWeapons() throws IOException {
        for (WeaponFamily family : WeaponFamily.values()) {
            if (family == WeaponFamily.RAM) {
                continue;
            }
            String token = family.name().toLowerCase(Locale.ROOT);
            String fireId = "weapon_fire_" + token;
            Waveform fire =
                    switch (family) {
                        case AUTOCANNON -> SoundSynth.weaponReport(420.0, 0.9, 0.28, seedFor(fireId));
                        case CANNON -> SoundSynth.weaponReport(150.0, 0.7, 0.95, seedFor(fireId));
                        case SHOTGUN -> SoundSynth.weaponReport(300.0, 1.0, 0.55, seedFor(fireId));
                        case ROCKET -> SoundSynth.weaponReport(220.0, 0.4, 1.30, seedFor(fireId));
                        case MORTAR -> SoundSynth.weaponReport(110.0, 0.3, 1.10, seedFor(fireId));
                        case FLAMER -> SoundSynth.weaponLoop(0.0, 700.0, 0.6, 1.2, seedFor(fireId));
                        case LASER -> SoundSynth.weaponLoop(220.0, 3400.0, 6.0, 1.2, seedFor(fireId));
                        case RAM -> throw new IllegalStateException("filtered above");
                    };
            write(
                    fireId,
                    fire,
                    AudioEvent.WEAPON_FIRE,
                    family.name(),
                    family.delivery() == WeaponFamily.Delivery.CONTINUOUS,
                    node -> node.put("weaponFamily", family.name()));

            String impactId = "weapon_impact_" + token;
            Waveform impact =
                    switch (family) {
                        case ROCKET, MORTAR -> SoundSynth.weaponReport(95.0, 0.5, 1.5, seedFor(impactId));
                        case FLAMER -> SoundSynth.weaponLoop(0.0, 480.0, 0.9, 0.9, seedFor(impactId));
                        case LASER -> SoundSynth.impact(AudioMaterial.METAL, 0.5, 0.6, seedFor(impactId));
                        default -> SoundSynth.impact(AudioMaterial.METAL, 0.8, 0.85, seedFor(impactId));
                    };
            write(
                    impactId,
                    impact,
                    AudioEvent.WEAPON_IMPACT,
                    family.name(),
                    family == WeaponFamily.FLAMER,
                    node -> node.put("weaponFamily", family.name()));
        }
    }

    // ---- Output -------------------------------------------------------------------------------

    /** Writes one sound and records its manifest row. */
    private void write(
            String id,
            Waveform wave,
            AudioEvent event,
            String key,
            boolean loop,
            java.util.function.Consumer<ObjectNode> extra)
            throws IOException {

        Path file = audioRoot.resolve(id + ".wav");
        wave.writeWav(file);

        ObjectNode node = mapper.createObjectNode();
        node.put("soundId", id);
        node.put("event", event.name());
        node.put("key", key);
        node.put("file", id + ".wav");
        node.put("loop", loop);
        node.put("durationSeconds", Math.round(wave.length() / (double) Waveform.SAMPLE_RATE_HZ * 1000d) / 1000d);
        extra.accept(node);
        entries.add(node);
    }

    private void writeManifest() throws IOException {
        ObjectNode root = mapper.createObjectNode();
        root.put("schemaVersion", "1.0.0");
        ArrayNode notes = root.putArray("notes");
        notes.add("Generated by asset-pipeline's SoundBankBuilder (docs/15_vehicle_preparation_pipeline.md#D15-S8).");
        notes.add("Do not hand-edit: re-run `./gradlew :asset-pipeline:buildSoundBank` instead.");
        notes.add("Sounds are per class and per material, never per vehicle (D15-R37): adding a car adds none.");
        notes.add("Every file is procedurally synthesised, so the bank carries this repository's licence and no");
        notes.add("second set of terms (D15-R39). See LICENCE.md beside this file.");
        root.put("sampleRateHz", Waveform.SAMPLE_RATE_HZ);
        root.put("channels", 1);
        root.put("bitsPerSample", 16);
        root.put("seed", BANK_SEED);

        ArrayNode sounds = root.putArray("sounds");
        // Sorted by id so the manifest is a stable diff whatever order the builders ran in.
        entries.stream()
                .sorted(java.util.Comparator.comparing(
                        node -> node.get("soundId").asText()))
                .forEach(sounds::add);

        mapper.writeValue(audioRoot.resolve(MANIFEST_FILE).toFile(), root);
    }

    /**
     * The licence file D15-R39 requires beside every audio asset.
     *
     * <p>Written by the generator rather than committed by hand, so it cannot drift from what the
     * bank actually contains — which is the failure mode a licence file has.
     */
    private void writeLicence() throws IOException {
        Files.writeString(
                audioRoot.resolve("LICENCE.md"),
                """
                # Audio licence

                Every file in this directory is **procedurally synthesised** by
                `asset-pipeline`'s `SoundBankBuilder` (`docs/15_vehicle_preparation_pipeline.md#D15-S8`).

                - **Source:** generated, not sampled or recorded. No third-party audio was used.
                - **Licence:** the same terms as this repository. No attribution to any third party
                  is required, and no third-party terms apply.
                - **Reproducible:** regenerating from the same seed produces byte-identical files, so
                  a rebuild is a no-op diff.

                This matters because D15-R39 requires every audio asset to record its licence, and the
                two shipped vehicle models are CC-BY-NC-SA. That constraint is already live; the point
                of synthesising the audio is that it does not add a second, differently-encumbered set
                of terms for somebody to discover later.

                To regenerate: `./gradlew :asset-pipeline:buildSoundBank`
                """);
    }

    /**
     * A per-sound seed derived from the bank seed and the sound's id.
     *
     * <p>Derived rather than sequential so that adding a sound in the middle of a builder does not
     * change the noise in every sound after it — which would turn a one-file change into a
     * forty-file diff.
     */
    static long seedFor(String soundId) {
        long hash = BANK_SEED;
        for (int i = 0; i < soundId.length(); i++) {
            hash = hash * 1_099_511_628_211L ^ soundId.charAt(i);
        }
        return hash;
    }
}
