/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.core.vehicle;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * {@code VEHICLES.md} is generated from {@link VehicleProfiles} and is kept current by this test.
 *
 * <p>The same discipline {@code INDEX.md} gets in the memory system: the file is generated, never
 * hand-edited, and something fails when the committed copy is stale. Here it is a test rather than a
 * Gradle task because the profiles are Java — a table generator outside {@code game-core} would need
 * to depend on it, and {@code asset-pipeline} sits at the same layer and may not (D02-S5.6).
 *
 * <p>Adding a vehicle therefore has a visible, mechanical consequence: the build fails until the
 * table is regenerated, which is the point. Run {@code ./gradlew :game-core:test} once and the file
 * is rewritten for you; run it again and it passes.
 */
@Tag("unit")
class VehicleTableTest {

    /** Where the generated table lives. */
    private static final String TABLE_FILE = "VEHICLES.md";

    /** Rewrites the table if it is stale, then fails so the change is committed deliberately. */
    @Test
    void theVehicleTableIsCurrent() throws IOException {
        assumeTrue(ShippedContent.isPresent(), "repository layout is not available");
        Path table = repositoryRoot().resolve(TABLE_FILE);
        String generated = render();

        if (!Files.exists(table) || !Files.readString(table).equals(generated)) {
            Files.writeString(table, generated);
            assertThat(false)
                    .as(
                            "%s was stale and has been regenerated from VehicleProfiles; review and commit it, "
                                    + "then re-run this test",
                            TABLE_FILE)
                    .isTrue();
        }
    }

    /** The whole document, so the generator has exactly one definition. */
    static String render() {
        StringBuilder out = new StringBuilder();
        out.append("# Syndicate — Vehicle Roster\n\n")
                .append("<!-- GENERATED FILE. Do not edit by hand. -->\n")
                .append("<!-- Source: game-core VehicleProfiles; regenerated by VehicleTableTest. -->\n\n")
                .append("Every vehicle the game ships, with the real car each was calibrated from. ")
                .append("Add a profile to `VehicleProfiles`, author its content under `assets/`, and ")
                .append("run `./gradlew :game-core:test` — this file is rewritten and the test fails ")
                .append("until the new copy is committed.\n\n")
                .append("**Names.** The in-game vehicle and the reference car are deliberately ")
                .append("different. Published performance figures are facts and free to use; a ")
                .append("manufacturer's name and model are trademarks, so they stay in the ")
                .append("`Reference` column and out of the game.\n\n");

        out.append("## Reference vehicles\n\n")
                .append("What the real cars do, as published by their makers.\n\n")
                .append("| Vehicle | Reference | Class | Kerb mass | Power | Torque | 0–100 km/h | Top speed"
                        + " | 100–0 | Cd | Wheelbase |\n")
                .append("|---|---|---|---|---|---|---|---|---|---|---|\n");
        for (VehicleProfile p : VehicleProfiles.all()) {
            out.append(String.format(
                    Locale.ROOT,
                    "| **%s** | %s | %s | %.0f kg | %.0f kW (%.0f hp) | %.0f N·m | %.2f s | %.0f km/h | %.1f m"
                            + " | %.2f | %.2f m |%n",
                    p.displayName(),
                    p.referenceVehicle(),
                    p.vehicleClass(),
                    p.kerbMassKg(),
                    p.enginePowerKw(),
                    p.enginePowerKw() * 1.341f,
                    p.engineTorqueNm(),
                    p.zeroToHundredS(),
                    p.topSpeedKph(),
                    p.brakingHundredToZeroM(),
                    p.dragCoefficientCd(),
                    p.wheelbaseM()));
        }

        out.append("\n## Simulation parameters\n\n")
                .append("What the game actually runs, derived from the figures above. ")
                .append("`Engine force` reproduces the published 0–100; `Power` is crank power after ")
                .append("driveline losses and is what caps force at speed; `k_drag` is ½·ρ·Cd·A.\n\n")
                .append("| Vehicle | Chassis / wheel mass | Engine force | Power at road | Brake force"
                        + " | k_drag | k_roll | Downforce | Derived top speed |\n")
                .append("|---|---|---|---|---|---|---|---|---|\n");
        for (VehicleProfile p : VehicleProfiles.all()) {
            out.append(String.format(
                    Locale.ROOT,
                    "| **%s** | %.0f / %.1f kg | %.0f N | %.0f kW | %.0f N | %.3f | %.3f | %.2f N/(m/s)²"
                            + " | %.0f km/h |%n",
                    p.displayName(),
                    p.chassisMassKg(),
                    p.wheelMassKg(),
                    p.engineForceN(),
                    p.enginePowerW() / 1000f,
                    p.brakeForceN(),
                    p.dragCoefficientNPerMps2(),
                    p.rollingResistance(),
                    p.downforceCoefficientNPerMps2(),
                    p.derivedTopSpeedKph()));
        }

        out.append("\n## Handling\n\n")
                .append("The numbers a tuning pass changes. Steering and grip are authored on the ")
                .append("wheel parts; aerodynamics on the chassis.\n\n")
                .append("| Vehicle | Steering lock | Steer rate | Tyre grip | Spring rate | Damping (comp/rel)"
                        + " | Roll influence | Wheel radius f/r | Track f/r |\n")
                .append("|---|---|---|---|---|---|---|---|---|\n");
        for (VehicleProfile p : VehicleProfiles.all()) {
            out.append(String.format(
                    Locale.ROOT,
                    "| **%s** | %.2f rad (%.0f°) | %.2f rad/s | %.2f | %.0f | %.2f / %.2f | %.2f | %.3f / %.3f m"
                            + " | %.2f / %.2f m |%n",
                    p.displayName(),
                    p.maxSteerRad(),
                    Math.toDegrees(p.maxSteerRad()),
                    p.steerRateRadPerSec(),
                    p.frictionSlip(),
                    p.suspensionStiffness(),
                    p.dampingCompression(),
                    p.dampingRelaxation(),
                    p.rollInfluence(),
                    p.wheelRadiusFrontM(),
                    p.wheelRadiusRearM(),
                    p.trackFrontM(),
                    p.trackRearM()));
        }

        out.append("\n## Content\n\n")
                .append("Where each vehicle's files live. Drop a `mesh.glb` into a part's directory ")
                .append("and it is that part's model — see `assets/README.md`.\n\n")
                .append("| Vehicle | Assembly | Chassis part | Wheel parts |\n")
                .append("|---|---|---|---|\n");
        for (VehicleProfile p : VehicleProfiles.all()) {
            String stem = p.profileId().value().replaceFirst("^vehicle_", "");
            out.append(String.format(
                    Locale.ROOT,
                    "| **%s** | `assets/vehicles/%s/` | `assets/parts/chassis_%s/` | `assets/parts/wheel_%s_front_01/`,"
                            + " `assets/parts/wheel_%s_rear_01/` |%n",
                    p.displayName(),
                    p.profileId().value(),
                    stem,
                    wheelStem(stem),
                    wheelStem(stem)));
        }

        out.append("\n## Sources\n\n");
        for (VehicleProfile p : VehicleProfiles.all()) {
            out.append(String.format(
                    Locale.ROOT, "- **%s** — %s. %s%n", p.displayName(), p.referenceVehicle(), p.referenceSource()));
        }
        out.append("\nFigures not published by the manufacturer are estimated from the vehicle's class ")
                .append("and labelled as estimates in the profile's Javadoc — for a race car that is ")
                .append("most of the aerodynamics.\n");
        return out.toString();
    }

    /** {@code apex_gt_01} to {@code apex}, which is how the wheel part ids are named. */
    private static String wheelStem(String chassisStem) {
        int cut = chassisStem.indexOf('_');
        return cut < 0 ? chassisStem : chassisStem.substring(0, cut);
    }

    private static Path repositoryRoot() {
        Path candidate = Path.of("").toAbsolutePath();
        for (int depth = 0; depth < 6 && candidate != null; depth++) {
            if (Files.isDirectory(candidate.resolve("assets")) && Files.isDirectory(candidate.resolve("docs"))) {
                return candidate;
            }
            candidate = candidate.getParent();
        }
        throw new IllegalStateException(
                "no repository root above " + Path.of("").toAbsolutePath());
    }
}
