/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.memory;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Renders {@code .agent-memory/INDEX.md} from the entry files
 * (docs/13_persistent_memory_system.md#D13-S5.5).
 *
 * <p>The index is fully generated and never hand-edited (D13-R8); lint rule L13 asserts the
 * committed file matches a freshly generated one. Generation is idempotent apart from the
 * {@code Generated:} line, which is what makes that comparison possible (AC-D13-7).
 *
 * <p>The {@code Blueprint Coverage} table at the end is an inverted index (D13-R10). It is the
 * reason "check memory before working in this domain" (read trigger RD2) is a cheap lookup rather
 * than a full-text search across every entry.
 */
public final class IndexGenerator {

    private IndexGenerator() {
        throw new AssertionError("no instances");
    }

    /** Renders the complete index. {@code today} is a parameter so tests can pin it. */
    public static String render(MemoryStore store, LocalDate today) {
        List<MemoryEntry> all = store.allEntries();
        long active = all.stream().filter(e -> "active".equals(e.status())).count();
        long superseded =
                all.stream().filter(e -> e.status().startsWith("superseded")).count();
        long resolved = all.stream().filter(e -> "resolved".equals(e.status())).count();

        StringBuilder out = new StringBuilder();
        out.append("# Agent Memory Index\n\n")
                .append("**Generated:** ")
                .append(today)
                .append("\n")
                .append("**Entries:** ")
                .append(all.size())
                .append(" (active: ")
                .append(active)
                .append(", superseded: ")
                .append(superseded)
                .append(", resolved: ")
                .append(resolved)
                .append(")\n\n")
                .append("> This file is generated by `memory-system`. Do not edit by hand.\n")
                .append("> Entry format and triggers: docs/13_persistent_memory_system.md#D13-S4.2\n");

        for (MemoryCategory category : MemoryCategory.values()) {
            renderCategory(out, category, store.entries(category));
        }
        renderCoverage(out, all);
        return out.toString();
    }

    private static void renderCategory(StringBuilder out, MemoryCategory category, List<MemoryEntry> entries) {
        out.append("\n## ").append(category.displayName()).append("\n\n");
        out.append("| ID | Title | Date | Status | Related Docs |\n");
        out.append("|---|---|---|---|---|\n");

        if (entries.isEmpty()) {
            out.append("| _(none yet)_ | | | | |\n");
            return;
        }
        for (MemoryEntry entry : entries) {
            out.append("| [")
                    .append(entry.id())
                    .append("](")
                    .append(category.directory())
                    .append('/')
                    .append(entry.id())
                    .append(".md) | ")
                    .append(entry.title())
                    .append(" | ")
                    .append(entry.date())
                    .append(" | ")
                    .append(entry.status())
                    .append(" | ")
                    .append(shortIds(entry))
                    .append(" |\n");
        }
        for (MemoryEntry entry : entries) {
            out.append("\n### ")
                    .append(entry.id())
                    .append(" — ")
                    .append(entry.title())
                    .append('\n')
                    .append(entry.summary())
                    .append('\n');
        }
    }

    /** The table shows bare section IDs; the full citation lives in the entry itself. */
    private static String shortIds(MemoryEntry entry) {
        if (entry.citesNothing()) {
            return "none";
        }
        List<String> ids =
                entry.citations().stream().map(MemoryEntry.Citation::sectionId).toList();
        return String.join(", ", ids);
    }

    private static void renderCoverage(StringBuilder out, List<MemoryEntry> all) {
        // TreeMap by document path so the ordering matches the document numbering (D13-R10).
        TreeMap<String, Set<String>> coverage = new TreeMap<>();
        for (MemoryEntry entry : all) {
            for (MemoryEntry.Citation citation : entry.citations()) {
                coverage.computeIfAbsent(citation.file(), key -> new TreeSet<>())
                        .add(entry.id());
            }
        }

        out.append("\n## Blueprint Coverage\n\n");
        out.append("| Doc | Entries referencing it |\n");
        out.append("|---|---|\n");
        if (coverage.isEmpty()) {
            out.append("| _(no citations yet)_ | |\n");
            return;
        }
        coverage.forEach((doc, ids) -> out.append("| ")
                .append(doc)
                .append(" | ")
                .append(String.join(", ", ids))
                .append(" |\n"));
    }

    /** Strips the {@code Generated:} line so two indexes can be compared for equality (L13). */
    public static String withoutGeneratedLine(String index) {
        return index.lines()
                .filter(line -> !line.startsWith("**Generated:**"))
                .reduce(new StringBuilder(), (sb, line) -> sb.append(line).append('\n'), StringBuilder::append)
                .toString();
    }
}
