/*
 * Syndicate — modular vehicular combat.
 * Implementation of the blueprint suite in docs/ (docs/00_master_index.md#D00-S4.2).
 */
package dev.syndicate.client.audio;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.Disposable;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.syndicate.model.AudioEvent;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The 52 synthesised sounds of {@code assets/audio/}, loaded and addressable
 * (docs/15_vehicle_preparation_pipeline.md#D15-S8, DEC-046).
 *
 * <p>The bank is generated by {@code asset-pipeline}'s {@code SoundBankBuilder} and described by
 * {@code audio.json}. This class reads that manifest and nothing else — it never guesses a filename
 * from an event and a key, because the manifest is the record of what was actually generated and a
 * guess would silently play nothing when the two drifted.
 *
 * <p>Sounds are addressed by {@code (event, key)}, which is the shape D15-R37 fixes: <b>per class
 * and per material, never per vehicle</b>. A new car adds no sound to this bank, and a new material
 * adds one row per event rather than one per car.
 *
 * <p><b>Degrades to silence rather than failing</b> (G18). A machine with no audio device — every CI
 * runner, and this project's own sandbox — still runs the client; {@link #isAvailable()} says so
 * once, in a log line, instead of throwing on the first gunshot.
 *
 * <p><b>Owner of every {@link Sound} it loads</b> (G19).
 */
public final class SoundBank implements Disposable {

    private static final Logger LOG = LoggerFactory.getLogger(SoundBank.class);

    /** Where the bank lives under the asset root (D15-S8). */
    public static final String AUDIO_DIRECTORY = "audio";

    /** The manifest the pipeline writes beside the wave files. */
    public static final String MANIFEST_FILE = "audio.json";

    private final Map<String, Sound> sounds = new TreeMap<>();
    private final Map<String, Entry> entries = new LinkedHashMap<>();
    private final boolean available;

    private SoundBank(boolean available) {
        this.available = available;
    }

    /** One row of the manifest: what a sound is and how it should be played. */
    public record Entry(String soundId, AudioEvent event, String key, boolean loop, float durationSeconds) {}

    /**
     * Loads the bank under an asset root.
     *
     * <p>A missing manifest, an unreadable one, or an absent audio device all produce an empty bank
     * rather than an exception. Every one of those is a content or environment problem, and none of
     * them is a reason a player cannot drive.
     */
    public static SoundBank load(Path assetRoot) {
        Objects.requireNonNull(assetRoot, "assetRoot");
        Path manifest = assetRoot.resolve(AUDIO_DIRECTORY).resolve(MANIFEST_FILE);
        if (!Files.isRegularFile(manifest)) {
            LOG.warn("no sound bank at {}; the game will be silent (D15-S8)", manifest);
            return new SoundBank(false);
        }
        if (Gdx.audio == null) {
            LOG.warn("no audio device; the sound bank is not loaded and the game will be silent");
            return new SoundBank(false);
        }

        SoundBank bank = new SoundBank(true);
        try {
            JsonNode root = new ObjectMapper().readTree(manifest.toFile());
            for (JsonNode node : root.path("sounds")) {
                bank.read(assetRoot, node);
            }
        } catch (IOException e) {
            LOG.error("sound bank manifest {} is unreadable; the game will be silent", manifest, e);
            return new SoundBank(false);
        }
        LOG.info("sound bank: {} sounds loaded from {}", bank.sounds.size(), manifest.getParent());
        return bank;
    }

    private void read(Path assetRoot, JsonNode node) {
        String soundId = node.path("soundId").asText(null);
        String eventName = node.path("event").asText(null);
        if (soundId == null || eventName == null) {
            return;
        }
        AudioEvent event;
        try {
            event = AudioEvent.valueOf(eventName);
        } catch (IllegalArgumentException e) {
            LOG.warn("sound {} names event {}, which is not in D15-S8's table; skipped", soundId, eventName);
            return;
        }
        Path file = assetRoot.resolve(AUDIO_DIRECTORY).resolve(node.path("file").asText(soundId + ".wav"));
        if (!Files.isRegularFile(file)) {
            LOG.warn("sound {} names {}, which is not on disk; skipped", soundId, file);
            return;
        }
        try {
            sounds.put(soundId, Gdx.audio.newSound(new FileHandle(file.toFile())));
            entries.put(
                    soundId,
                    new Entry(
                            soundId,
                            event,
                            node.path("key").asText(""),
                            node.path("loop").asBoolean(false),
                            (float) node.path("durationSeconds").asDouble(0.0)));
        } catch (RuntimeException e) {
            LOG.warn("sound {} could not be decoded; skipped", soundId, e);
        }
    }

    /** True when there is a device and at least one sound. */
    public boolean isAvailable() {
        return available && !sounds.isEmpty();
    }

    /** How many sounds are resident. */
    public int size() {
        return sounds.size();
    }

    /** The sound with an id, or null. */
    public Sound get(String soundId) {
        return soundId == null ? null : sounds.get(soundId);
    }

    /**
     * The sound for an event and a key, e.g. {@code (IMPACT, "metal_heavy")}.
     *
     * <p>The id convention is the pipeline's: {@code <event token>_<key>}, lower case. It is
     * reconstructed rather than looked up by key because the manifest's {@code key} field carries the
     * enum spelling ({@code METAL}) while the filename carries the token ({@code metal}), and the
     * filename is the thing that has to match.
     */
    public Sound forKey(AudioEvent event, String key) {
        if (event == null) {
            return null;
        }
        String id = key == null || key.isEmpty()
                ? event.token()
                : event.token() + "_" + key.toLowerCase(java.util.Locale.ROOT);
        return sounds.get(id);
    }

    /** The manifest row for a sound id, or null. */
    public Entry entry(String soundId) {
        return entries.get(soundId);
    }

    @Override
    public void dispose() {
        sounds.values().forEach(Sound::dispose);
        sounds.clear();
        entries.clear();
    }
}
