"""Fracture site generation (D09-S5.2 step 2a).

Sites are generated by the tool's own PCG32 and never by Blender's randomness. D09-S5.2
gives the reason: the operator's own source modes depend on scene state the tool does not
fully control, so explicit sites are the only way G11 survives a Blender patch release.

Kept free of ``bpy`` so the distributions are unit-testable, which matters more here than
anywhere else in the tool — a site generator that quietly clusters produces a fracture that
looks plausible and conserves mass while being visually wrong in a way no numeric check
catches.
"""

from __future__ import annotations

from collections.abc import Callable

from .geometry import Aabb, Vec3, add, distance, normalize, scale, sub
from .rng import Pcg32

# Sampling budget per site before ``uniform`` gives up on the spacing constraint. Generous,
# because a rejection failure produces a worse fracture rather than an error.
_MAX_ATTEMPTS_PER_SITE = 200


def uniform_sites(
    count: int,
    bbox: Aabb,
    rng: Pcg32,
    inside: Callable[[Vec3], bool],
) -> list[Vec3]:
    """Poisson-ish sites, rejection-sampled for a minimum spacing (D09-S5.2).

    The spacing constraint is what makes shards comparable in size. Sampling without it
    produces clusters, and a cluster of Voronoi sites produces slivers between a few huge
    cells — technically a valid fracture, and a bad-looking one.

    The constraint is relaxed rather than enforced: when the budget runs out, whatever was
    placed is returned. A thin plate genuinely cannot hold 24 well-spaced sites, and failing
    there would reject legitimate content.
    """
    min_dist = (bbox.volume / max(count, 1)) ** (1.0 / 3.0) * 0.55
    sites: list[Vec3] = []
    attempts = 0
    budget = count * _MAX_ATTEMPTS_PER_SITE

    while len(sites) < count and attempts < budget:
        attempts += 1
        point = _sample_box(bbox, rng)
        if not inside(point):
            continue
        if all(distance(point, s) >= min_dist for s in sites):
            sites.append(point)

    # Second pass without the spacing constraint, so a part that is simply too small to
    # space `count` sites still fractures into roughly the requested number of pieces.
    while len(sites) < count and attempts < budget * 2:
        attempts += 1
        point = _sample_box(bbox, rng)
        if inside(point):
            sites.append(point)

    return sort_sites(sites)


def surface_biased_sites(
    count: int,
    bbox: Aabb,
    rng: Pcg32,
    surface_sampler: Callable[[Pcg32], tuple[Vec3, Vec3]],
) -> list[Vec3]:
    """Sites pushed just inside the surface (D09-S5.2).

    Real plate damage shatters near the skin, so biasing sites outward produces many small
    surface shards and a few large interior ones. ``surface_sampler`` returns a point and
    its outward normal; the site is placed inward along that normal.
    """
    inward_bias = 0.15 * bbox.min_extent
    sites: list[Vec3] = []
    for _ in range(count):
        point, normal = surface_sampler(rng)
        sites.append(add(point, scale(normalize(normal), -inward_bias)))
    return sort_sites(sites)


def impact_biased_sites(
    count: int,
    bbox: Aabb,
    rng: Pcg32,
    impact: Vec3,
    clamp: Callable[[Vec3], Vec3],
) -> list[Vec3]:
    """Sites dense at an impact point and sparse away from it (D09-S5.2).

    The radius uses ``U^(1/3)`` rather than ``U`` so that sites are uniform *per unit
    volume* out to the maximum radius. Sampling the radius uniformly would put equal counts
    in every shell, which — since outer shells hold far more volume — inverts the intended
    bias and clusters everything at the centre.
    """
    max_radius = bbox.max_extent * 0.6
    sites: list[Vec3] = []
    for _ in range(count):
        direction = rng.unit_vector()
        radius = (rng.next_float() ** (1.0 / 3.0)) * max_radius
        sites.append(clamp(add(impact, scale(direction, radius))))
    return sort_sites(sites)


def sort_sites(sites: list[Vec3]) -> list[Vec3]:
    """Lexicographic order (D09-R10, G11).

    Cell order must not depend on the order sites happened to be accepted by rejection
    sampling. Sorted before use here and re-sorted by centroid after generation, because
    neither sort alone is enough: the first fixes the input order, the second fixes the
    output order the clipping stage produces.
    """
    return sorted(sites, key=lambda p: (p[0], p[1], p[2]))


def bisector_planes(site: Vec3, others: list[Vec3]) -> list[tuple[Vec3, float]]:
    """Half-spaces whose intersection is ``site``'s Voronoi cell.

    A Voronoi cell is by definition the set of points closer to its site than to any other,
    and "closer to A than to B" is exactly the half-space bounded by the perpendicular
    bisector of AB. Intersecting those half-spaces is therefore not an approximation of the
    cell — it is the cell, which is what makes this construction a valid replacement for
    the voro++ call D09-S5.2 assumes (see DEV-002).

    Returned as ``(normal, offset)`` with the cell on the ``dot(n, p) <= offset`` side.
    """
    planes: list[tuple[Vec3, float]] = []
    for other in others:
        delta = sub(other, site)
        norm = normalize(delta)
        if norm == (0.0, 0.0, 0.0):
            continue  # coincident sites contribute no constraint
        midpoint = scale(add(site, other), 0.5)
        planes.append((norm, norm[0] * midpoint[0] + norm[1] * midpoint[1] + norm[2] * midpoint[2]))
    return planes


def _sample_box(bbox: Aabb, rng: Pcg32) -> Vec3:
    return (
        rng.uniform(bbox.min[0], bbox.max[0]),
        rng.uniform(bbox.min[1], bbox.max[1]),
        rng.uniform(bbox.min[2], bbox.max[2]),
    )
